name: bazaar_bihar
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.6
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  dio: ^4.0.0
  convex_bottom_bar: ^3.0.0
  stacked_card_carousel: ^0.0.3-nullsafety.1
  carousel_slider: ^4.0.0
  flip_card: ^0.5.0
  flutter_icons: ^1.1.0
  shrink_sidemenu: ^2.0.0+1-null-safety
  easy_mask: ^2.0.1
  connectivity: ^3.0.6
  badges: ^2.0.1
  in_app_update: ^2.0.0
  cached_network_image: ^3.1.0
  razorpay_flutter: ^1.2.7



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/loaders/

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
