name: bazaar_bihar
description: A ecommerce flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+29


environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.6
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  dio: ^5.0.3
  convex_bottom_bar: ^3.0.0
  stacked_card_carousel: ^0.0.3-nullsafety.1
  carousel_slider: ^4.0.0
  flutter_icons_null_safety: ^1.1.0
  shrink_sidemenu: ^2.0.0+1-null-safety
  easy_mask: ^2.0.1
  connectivity_plus: ^1.1.0
  badges: ^2.0.1
  cached_network_image: ^3.1.0
  razorpay_flutter: ^1.2.7
  intl: ^0.17.0
  image_picker: ^0.8.3+3
  new_version: ^0.2.0
  flutter_easyloading: ^3.0.3
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  firebase_messaging: ^10.0.8
  google_sign_in: ^5.0.0
  firebase_analytics: ^5.0.2
  ej_selector: ^1.0.0
  dropdown_search: ^1.0.0
  cashfree_pg: ^2.0.3+23
  easy_rich_text: ^0.5.7
  image_crop: ^0.4.0
  simple_s3: ^0.3.2
  flutter_rating_bar: ^4.0.0
  flutter_local_notifications: ^8.2.0
  device_info: ^2.0.2
  animated_text_kit: ^4.2.1
  widget_marquee: ^0.0.5
  division: ^0.9.0


dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.2.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/loaders/
